name: 'Integration Test'

on:
  schedule:
    - cron:  '30 20 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - uses: actions/github-script@v3
      id: create-branch
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const integrationBranchName = `refs/heads/integration-branch-${Date.now()}`
          core.setOutput('GITHUB_INTEGRATION_BRANCH', integrationBranchName);

          const refData = await github.repository.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/dev',
            });

          await github.repository.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: integrationBranchName,
            sha: refData.data.object.sha,
          })
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run integration-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_INTEGRATION_BRANCH: ${{ steps.create-branch.outputs.GITHUB_INTEGRATION_BRANCH }}
