name: 'Integration Test'

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - name: Badge Coverage With Provided Url
      id: jest-coverage-with-url
      uses: luk-schweizer/jest-code-coverage-badge-action@dev
      with:
        kvaas-key-url: 'https://api.keyvalue.xyz/7732e373/coverage'
        test-command: 'npx jest --coverage integration/dummy.test.js'
    - run: echo "${{ steps.jest-coverage-with-url.BADGE_URL }}"
    - name: Badge Coverage With No Provided Url
      id: jest-coverage-without-url
      uses: luk-schweizer/jest-code-coverage-badge-action@dev
      with:
        badge-label: 'coverageWithUrlProvided'
        test-command: 'npx jest --coverage integration/dummy.test.js'
    - run: echo "${{ steps.jest-coverage-without-url.BADGE_URL }}"
    - run: npm run integration-test
      env:
        BADGE_OUTPUT_WITH_URL_PROVIDED: ${{ steps.jest-coverage-with-url.BADGE_URL }}
        BADGE_OUTPUT_WITH_URL_NOT_PROVIDED: ${{ steps.jest-coverage-without-url.BADGE_URL }}