name: 'Integration Test'

on:
  schedule:
    - cron:  '30 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run integration-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WORKFLOW_ID_FOR_TEST: 'workflow-for-integration-test.yml'
        REPOSITORY_REF: 'heads/dev'
