name: build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run coverage
      if: ${{ matrix.node-version != '15.x'}}
    - name: Badge Coverage
      id: jest-coverage
      uses: luk-schweizer/jest-code-coverage-badge-action@dev
      if: ${{ matrix.node-version == '15.x'}}
      with:
        kvaas-key-url: 'https://api.keyvalue.xyz/b78465cf/coverage'
        test-command: 'npm run coverage'
    - run: echo "${{ steps.jest-coverage.outputs.BADGE_URL }}"